fabricdemo:
  target: dev
  outputs:
    dev:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: 'ci3bol2fn4qelhpygll3uxzmiq-42i322e22fhuxp7cvunr33un5i.datawarehouse.pbidedicated.windows.net'
      port: 1433
      database: DATAWH
      schema: dbo
      authentication: ActiveDirectoryInteractive
      user: ttnghia@cmc.com.vn